@startuml classes
set namespaceSeparator none
class "ProcessOriginal" as src.bully_orginal.ProcessOriginal {
  _id
  coordinator : NoneType
  coordinator_msg_sent : bool
  election_msg_sent : bool
  message_queue : Queue
  message_thread : Thread
  msg_count : int
  oks : int
  processes : list
  state
  stop_worker : Event
  __init__(_id)
  enqueue_message(sender_id, msg_type)
  get_id()
  get_process(_id)
  kill()
  message_handler(process_id, msg_type)
  send_coordinator()
  start_election()
  start_thread()
  state_machine()
}
@enduml
